---
name: File-RandomLine
version: !!perl/hash:Module::Build::Version
  original: 0.18
  version:
    - 0
    - 180
author:
  - 'David A Golden <dagolden@cpan.org>'
abstract: Retrieve random lines from a file
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  File::Spec: 0.87
  Test::Exception: 0.2
  Test::MockRandom: 0.97
  Test::More: 0.6
  Test::Warn: 0.08
  Want: 0.08
  perl: 5.006
provides:
  File::RandomLine:
    file: lib/File/RandomLine.pm
    version: 0.18
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
